#!/usr/bin/env python3
"""
build_shared_tokens.py — Regenerate hyperframes-scenes/shared/tokens.css from
design-tokens.json. Also validates that remotion-studio/src/theme/brand.ts
values match the JSON (warns on drift).

Workflow:
  1. Edit design-tokens.json (source of truth)
  2. Run this script
  3. Commit both the JSON and the regenerated tokens.css
  4. If brand.ts drift warnings appear, manually update brand.ts to match

Why: the dual-engine pipeline (Remotion + Hyperframes) requires both engines
to render every scene with identical palette / fonts / easing / timing. This
script enforces that by generating the Hyperframes CSS from the same JSON that
brand.ts was derived from.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path("/Users/digischola/Desktop/Digischola")
# Post-2026-04-29 _engine/ convention: media build dirs live under brand/_engine/.
TOKENS_JSON = REPO / "brand/_engine/remotion-studio/src/theme/design-tokens.json"
TOKENS_CSS = REPO / "brand/_engine/hyperframes-scenes/shared/tokens.css"
BRAND_TS = REPO / "brand/_engine/remotion-studio/src/theme/brand.ts"


def generate_tokens_css(tokens: dict) -> str:
    """Emit a CSS file with :root custom properties + font @imports for Hyperframes."""
    palette = tokens["palette"]
    fonts = tokens["fonts"]
    weights = tokens["weights"]
    easing = tokens["easingCSS"]
    canvas = tokens["canvas"]
    scene = tokens["sceneDuration"]
    sub = tokens["subtitle"]

    lines = [
        "/* AUTOGENERATED by scripts/build_shared_tokens.py — DO NOT EDIT BY HAND.",
        f"   Source of truth: design-tokens.json ({tokens.get('version', '?')})",
        "   Every Hyperframes composition should <link rel=\"stylesheet\" href=\"../shared/tokens.css\"> */",
        "",
        "@import url(\"https://fonts.googleapis.com/css2?family=Orbitron:wght@700;900&family=Space+Grotesk:wght@500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap\");",
        "",
        ":root {",
        "  /* ── Palette ────────────────────────────────────────────────── */",
    ]
    for k, v in palette.items():
        # camelCase → kebab-case
        css_key = re.sub(r"([A-Z])", r"-\1", k).lower()
        lines.append(f"  --color-{css_key}: {v};")
    lines.append("")
    lines.append("  /* ── Fonts ──────────────────────────────────────────────────── */")
    for k, v in fonts.items():
        lines.append(f"  --font-{k}: {v};")
    lines.append("")
    lines.append("  /* ── Weights ────────────────────────────────────────────────── */")
    for k, v in weights.items():
        css_key = re.sub(r"([A-Z])", r"-\1", k).lower()
        lines.append(f"  --weight-{css_key}: {v};")
    lines.append("")
    lines.append("  /* ── Easing (CSS cubic-bezier) ──────────────────────────────── */")
    for k, v in easing.items():
        css_key = re.sub(r"([A-Z])", r"-\1", k).lower()
        lines.append(f"  --ease-{css_key}: {v};")
    lines.append("")
    lines.append("  /* ── Canvas ─────────────────────────────────────────────────── */")
    lines.append(f"  --canvas-width: {canvas['width']}px;")
    lines.append(f"  --canvas-height: {canvas['height']}px;")
    lines.append(f"  --canvas-fps: {canvas['fps']};")
    lines.append(f"  --safe-horiz: {canvas['safeHoriz']}px;")
    lines.append(f"  --max-text-width: {canvas['maxTextWidth']}px;")
    lines.append("")
    lines.append("  /* ── Scene durations (seconds) ──────────────────────────────── */")
    for k, v in scene.items():
        css_key = k.replace("_", "-")
        lines.append(f"  --dur-{css_key}: {v}s;")
    lines.append("")
    lines.append("  /* ── Subtitle tokens ────────────────────────────────────────── */")
    lines.append(f"  --subtitle-anchor-y: {sub['anchorY']}px;")
    for school in ("A", "B"):
        s = sub[school]
        lines.append(f"  --subtitle-{school}-font: var(--font-{s['fontFamilyKey']});")
        lines.append(f"  --subtitle-{school}-weight: var(--weight-{s['fontWeightKey'].replace('orbitron', 'orbitron-').replace('grotesk', 'grotesk-').replace('manrope', 'manrope-').rstrip('-')});")
        lines.append(f"  --subtitle-{school}-size: {s['fontSize']}px;")
        lines.append(f"  --subtitle-{school}-letter-spacing: {s['letterSpacing']};")
        lines.append(f"  --subtitle-{school}-line-height: {s['lineHeight']};")
    lines.append("}")
    lines.append("")
    lines.append("/* ── Shared atmospheric mesh (matches Remotion CSS mesh — keeps both engines visually aligned) */")
    lines.append(".atmo-mesh-neutral {")
    lines.append("  position: absolute; inset: 0;")
    lines.append("  background:")
    lines.append("    radial-gradient(1100px 700px at 30% 15%, rgba(59, 158, 255, 0.18) 0%, rgba(59, 158, 255, 0) 55%),")
    lines.append("    radial-gradient(950px 650px at 75% 80%, rgba(74, 222, 128, 0.14) 0%, rgba(74, 222, 128, 0) 55%),")
    lines.append("    linear-gradient(140deg, #0B1224 0%, var(--color-bg-dark) 100%);")
    lines.append("  animation: atmo-shift 7s ease-in-out infinite alternate;")
    lines.append("}")
    lines.append(".atmo-mesh-positive {")
    lines.append("  position: absolute; inset: 0;")
    lines.append("  background:")
    lines.append("    radial-gradient(1200px 800px at 25% 20%, rgba(74, 222, 128, 0.28) 0%, rgba(74, 222, 128, 0) 55%),")
    lines.append("    radial-gradient(900px 700px at 80% 70%, rgba(59, 158, 255, 0.22) 0%, rgba(59, 158, 255, 0) 55%),")
    lines.append("    linear-gradient(135deg, #0A1020 0%, var(--color-bg-dark) 100%);")
    lines.append("  animation: atmo-shift 6s ease-in-out infinite alternate;")
    lines.append("}")
    lines.append(".atmo-mesh-warning {")
    lines.append("  position: absolute; inset: 0;")
    lines.append("  background:")
    lines.append("    radial-gradient(1000px 700px at 70% 25%, rgba(239, 68, 68, 0.22) 0%, rgba(239, 68, 68, 0) 55%),")
    lines.append("    radial-gradient(900px 650px at 25% 75%, rgba(148, 163, 184, 0.12) 0%, rgba(148, 163, 184, 0) 55%),")
    lines.append("    linear-gradient(130deg, #12101A 0%, var(--color-bg-dark) 100%);")
    lines.append("  animation: atmo-shift 6.5s ease-in-out infinite alternate;")
    lines.append("}")
    lines.append("@keyframes atmo-shift {")
    lines.append("  0% { transform: scale(1) translate(0, 0); filter: hue-rotate(0deg); }")
    lines.append("  100% { transform: scale(1.04) translate(-1.5%, 1%); filter: hue-rotate(4deg); }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def validate_brand_ts(tokens: dict) -> list[str]:
    """Check that brand.ts contains values matching the JSON. Returns list of warnings."""
    warnings = []
    if not BRAND_TS.exists():
        return [f"brand.ts not found at {BRAND_TS}"]
    text = BRAND_TS.read_text(encoding="utf-8")

    # Spot-check palette hex values appear somewhere in brand.ts
    for k, v in tokens["palette"].items():
        if isinstance(v, str) and v.startswith("#") and v not in text:
            warnings.append(f"palette.{k} = {v} not found in brand.ts")

    # Spot-check scene durations
    for k, v in tokens["sceneDuration"].items():
        # Look for e.g. `hook: 2.9` in brand.ts
        if not re.search(rf"{re.escape(k)}:\s*{re.escape(str(v))}", text):
            warnings.append(f"sceneDuration.{k} = {v} may differ in brand.ts (pattern not found)")

    # Spot-check subtitle anchor
    anchor_y = tokens["subtitle"]["anchorY"]
    if f"anchorY: {anchor_y}" not in text:
        warnings.append(f"subtitle.anchorY = {anchor_y} not found in brand.ts")

    return warnings


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="Only validate drift; don't write tokens.css")
    args = ap.parse_args()

    if not TOKENS_JSON.exists():
        sys.exit(f"Source not found: {TOKENS_JSON}")

    tokens = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    print(f"▶ Loaded design-tokens.json ({tokens.get('version', '?')})")

    # Validate brand.ts parity
    warnings = validate_brand_ts(tokens)
    if warnings:
        print(f"\n⚠ brand.ts drift check — {len(warnings)} warnings:")
        for w in warnings:
            print(f"  • {w}")
        print("  (edit brand.ts to match JSON; these warnings don't block generation)")
    else:
        print("✓ brand.ts values align with design-tokens.json")

    if args.check:
        sys.exit(1 if warnings else 0)

    # Generate tokens.css
    css = generate_tokens_css(tokens)
    TOKENS_CSS.parent.mkdir(parents=True, exist_ok=True)
    TOKENS_CSS.write_text(css, encoding="utf-8")
    size = TOKENS_CSS.stat().st_size
    print(f"\n✓ Wrote {TOKENS_CSS} ({size:,} bytes)")


if __name__ == "__main__":
    main()
